---
name: Perf report
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
      fail-fast: false
    name: Performance report using Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dot
        run: sudo apt-get install graphviz -y

      - name: Install perf8
        run: |
          python3 -m venv .
          bin/pip install -r requirements.txt
          bin/pip install -e .

      - name: Run Perf test
        run: bin/perf8 --all -c perf8/tests/ademo.py

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: /home/runner/work/perf8/perf8/perf8-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
